kind: Cluster
name: c2
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
networking:
  podSubnet: "10.110.0.0/16"
  serviceSubnet: "10.111.0.0/16"
#  disableDefaultCNI: true
